### PR TITLE
Pretty print if running from interactive shell

### PR DESCRIPTION
**Pull request by stephenfin**

### CODE REVIEW

**Comment by stephenfin** [comment]
Merged into https://github.com/shiftstack/prune/pull/17

**Comment by pierreprinetti** [comment]
I have nothing against this change. However, I am pretty-printing on-demand by piping to `jq`. I also get nice colours. Would that work for you?

**Comment by stephenfin** [comment]
If there's a big downside to dragging in `golang.org/x/term`, then I can just do as you do. If not though, this will always do the right thing - even when I inevitably forget to pipe to `jq` - and is therefore a good quality of life improvement worth adding IMO :smile:

**Review by pierreprinetti — APPROVED** [review]

**Pull request merged**
